
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost 
  username: app
  password: password

development:
  <<: *default
  database: scribblenauts_app_development

test:
  <<: *default
  database: scribblenauts_app_test

production:
  <<: *default
  database: scribblenauts_app_production
  username: scribblenauts_app
  password: <%= ENV["SCRIBBLENAUTS_APP_DATABASE_PASSWORD"] %>
